# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fuku < Formula
  desc "Lightweight CLI orchestrator for running and managing multiple local services"
  homepage "https://tab.github.io/fuku/"
  version "0.16.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tab/fuku/releases/download/v0.16.0/fuku_v0.16.0_macos_x86_64.tar.gz"
      sha256 "d04eb4d0934020d9923e5ed048175751311f96d7efb7d8d33af9be797cef5dd8"

      define_method(:install) do
        bin.install "fuku"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tab/fuku/releases/download/v0.16.0/fuku_v0.16.0_macos_arm64.tar.gz"
      sha256 "496dd00dc8321f9adb4567a3234c97ef8775a2b9280c2cdcceaa000877b1cc00"

      define_method(:install) do
        bin.install "fuku"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tab/fuku/releases/download/v0.16.0/fuku_v0.16.0_linux_x86_64.tar.gz"
      sha256 "4ac9a42803e0f2c9f1bf95070e1de93de1dc7992cbffdb3cd209c038621380b9"
      define_method(:install) do
        bin.install "fuku"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/tab/fuku/releases/download/v0.16.0/fuku_v0.16.0_linux_arm.tar.gz"
      sha256 "8011ed4e0ea98e44b52d13bc4fbd145c30702662f5c7ec6119e33fb67e91514d"
      define_method(:install) do
        bin.install "fuku"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tab/fuku/releases/download/v0.16.0/fuku_v0.16.0_linux_arm64.tar.gz"
      sha256 "00b68faddc819fa9db929874f412510e9cc81ccc2e0505b6474553ab57192a9b"
      define_method(:install) do
        bin.install "fuku"
      end
    end
  end

  test do
    system "#{bin}/fuku", "version"
  end
end
