# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fuku < Formula
  desc "Lightweight CLI orchestrator for running and managing multiple local services"
  homepage "https://tab.github.io/fuku/"
  version "0.19.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tab/fuku/releases/download/v0.19.0/fuku_v0.19.0_macos_x86_64.tar.gz"
      sha256 "bff7b03ce720669da1ef787a2384a6645cabee9ebae2923a3688032b8c80027f"

      define_method(:install) do
        bin.install "fuku"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tab/fuku/releases/download/v0.19.0/fuku_v0.19.0_macos_arm64.tar.gz"
      sha256 "00d5a22bfb58984964e2f1ee39f1b3b569920a91376bcc959fc337922df88bd7"

      define_method(:install) do
        bin.install "fuku"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tab/fuku/releases/download/v0.19.0/fuku_v0.19.0_linux_x86_64.tar.gz"
      sha256 "87702cb2e03946672d3510fc7afa0cf5f5c5b8e269847355832f4ddcad1719dc"
      define_method(:install) do
        bin.install "fuku"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/tab/fuku/releases/download/v0.19.0/fuku_v0.19.0_linux_arm.tar.gz"
      sha256 "5d56daa28d757ce3d734a4879127ce7d10ce7d300e20a0c6947572ff0d461fb7"
      define_method(:install) do
        bin.install "fuku"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tab/fuku/releases/download/v0.19.0/fuku_v0.19.0_linux_arm64.tar.gz"
      sha256 "afcdcbaa7493716d449cc3bcb99b05a827eca9baefddf13332e0e95dd1837854"
      define_method(:install) do
        bin.install "fuku"
      end
    end
  end

  test do
    system "#{bin}/fuku", "version"
  end
end
