# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fuku < Formula
  desc "Lightweight CLI orchestrator for running and managing multiple local services"
  homepage "https://tab.github.io/fuku/"
  version "0.19.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tab/fuku/releases/download/v0.19.1/fuku_v0.19.1_macos_x86_64.tar.gz"
      sha256 "2753fe5392ab4a2b1be0e3b6e4988f7d8f1e15f2504a619950fca3597ba3cf5c"

      define_method(:install) do
        bin.install "fuku"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tab/fuku/releases/download/v0.19.1/fuku_v0.19.1_macos_arm64.tar.gz"
      sha256 "0c99235039e5558549903b9354a08150351a88eb927260849ffecb38d9c59e3c"

      define_method(:install) do
        bin.install "fuku"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tab/fuku/releases/download/v0.19.1/fuku_v0.19.1_linux_x86_64.tar.gz"
      sha256 "b96dbe9eed5b0c1c18a813dde25f3b9d3dd6d2dae3eca820b6b175b9060ec3db"
      define_method(:install) do
        bin.install "fuku"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/tab/fuku/releases/download/v0.19.1/fuku_v0.19.1_linux_arm.tar.gz"
      sha256 "a8cbd92683e94f32d330ae84501a394cb7b189530da6de2e613a9ec7cd2fe239"
      define_method(:install) do
        bin.install "fuku"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tab/fuku/releases/download/v0.19.1/fuku_v0.19.1_linux_arm64.tar.gz"
      sha256 "c7019c79a29f45e928a5113345f890b2da50cad3dd9ce60b63b1ae10dc8617d3"
      define_method(:install) do
        bin.install "fuku"
      end
    end
  end

  test do
    system "#{bin}/fuku", "version"
  end
end
